### ISSUE TITLE
Replace hand-drawn project icon placeholders with higher quality icons

### ISSUE THREAD

**Issue by cscairns** [khandelwal/dhsnext#6]

**Comment by khandelwal** [comment]
Fixed, although the hand-drawn project icons convey an authenticity and sense of fun these don't. 


![screen shot 2017-01-18 at 3 45 24 pm](https://cloud.githubusercontent.com/assets/636752/22082320/402db5b8-dd95-11e6-887d-67f2dd3c0744.png)
